use chezmoi template for os detection

diff --git a/dot_bashrc b/dot_bashrc
--- a/dot_bashrc
+++ b/dot_bashrc
@@ -6,10 +6,11 @@
 # here.
 #
 
-# TODO: remove any [ ] && ... => those keep the !=0 exit code if false
-# TODO: move MY_OS to different name and a script that gets sourced
-# (.bashrc_template) and let it be generated by .bashrc_template.tmpl (chezmoi).
-# => stronger way to detect os then in bash; source it at the very top
+tmp="${HOME}/.bashrc_chezmoi_generated" 
+if [ -f "$tmp" ]; then
+	. "$tmp"
+fi
+tmp=
 
 # If not running interactively, don't do anything
 case $- in
@@ -53,25 +54,18 @@ case "$TERM" in
 	xterm-color|*-256color) color_prompt=yes;;
 esac
 
-if [ "${OSTYPE#darwin}" != "$OSTYPE" ]; then
-	MY_OS='mac'
-	OS_COLOR="01;37" # white
-	# TODO: move this to the top below OS detection
-	eval `/usr/libexec/path_helper -s`
-elif [ -f "/etc/os-release" ]; then
-	MY_OS="$(grep -w ID "/etc/os-release" | cut -d= -f2 | tr -d '"')"
-	case "$MY_OS" in
-		ubuntu) OS_COLOR="01;31" ;; # red
-		arch)   OS_COLOR="01;36" ;; # cyan
-		*)      OS_COLOR="01;32" ;; # green
-	esac
-else
-	MY_OS="unknown"
-	OS_COLOR="01;31"
+ps1_os_name="${dz_os_name:-"${SHELL}"}" # clear that something went wrong
+if [ -n "$dz_os_name" ]; then
+	case "${dz_os_name,,}" in
+		*mac*)    ps1_os_color="01;37" ;; # white
+		*ubuntu*) ps1_os_color="01;31" ;; # red
+		*arch*)   ps1_os_color="01;36" ;; # cyan
+		*)        ps1_os_color="01;32" ;; # green
+	esac		
 fi
 
 if [ "$color_prompt" = yes ]; then
-	PS1='${debian_chroot:+($debian_chroot)}[\[\033[${OS_COLOR}m\]${MY_OS}\[\033[00m\]]:\[\033[01;34m\]\w\[\033[00m\]\$ '
+	PS1='${debian_chroot:+($debian_chroot)}[\[\033[${ps1_os_color}m\]${ps1_os_name}\[\033[00m\]]:\[\033[01;34m\]\w\[\033[00m\]\$ '
 else
 	PS1='${debian_chroot:+($debian_chroot)}[${MY_OS}]:\w\$ '
 fi
@@ -110,7 +104,7 @@ if ! shopt -oq posix; then
 		. /usr/share/bash-completion/bash_completion
 	elif [ -f /etc/bash_completion ]; then
 		. /etc/bash_completion
-	# Mac (intel and arm):
+		# Mac (intel and arm):
 	elif [ -f /usr/local/etc/bash_completion ]; then
 		. /usr/local/etc/bash_completion
 	elif [ -f /opt/homebrew/etc/profile.d/bash_completion.sh ]; then
@@ -130,9 +124,8 @@ export XDG_DATA_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}"
 [ -d "${XDG_DATA_HOME}" ] || mkdir -p "${XDG_DATA_HOME}"
 export XDG_STATE_HOME="${XDG_STATE_HOME:-${HOME}/.local/state}"
 [ -d "${XDG_STATE_HOME}" ] || mkdir -p "${XDG_STATE_HOME}"
-# TODO: change this to not depend on XDG_DATA_DIRS being in the front. 
 case "$XDG_DATA_DIRS" in
-	"$XDG_DATA_HOME"*) ;; # XDG_DATA_HOME already appended.
+	*"$XDG_DATA_HOME"*) ;; # XDG_DATA_HOME already appended.
 	*)
 		export XDG_DATA_DIRS="${XDG_DATA_HOME}:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
 		;;
@@ -147,7 +140,7 @@ fi
 # times in nested shells).
 if [ "$CHEZMOI" = "1" ]; then
 	case "$PS1" in
-		"(chezmoi)"*) ;;
+		*"(chezmoi)"*) ;;
 		*)
 			PS1="(chezmoi)${PS1}";;
 	esac
@@ -216,17 +209,19 @@ if command -v chezmoi >/dev/null; then
 		shift
 		case "$cmd" in
 			s) cmd="status";;
+			e) cmd="edit";;
 			a) cmd="add";;
 			r) cmd="re-add";;
-      f) cmd="forget";;
+			f) cmd="forget";;
 			d) cmd="diff";;
 			l) cmd="list";;
 			m) cmd="managed";;
 			p) cmd="source-path";;
 			h)
-				cat <<'EOF'
+				cat <<-'EOF' # for now <<- in case of gg=G
 ch overwites the first arg if it's one of these: chezmoi [arg] <remaining args>
 s  status
+e  edit
 a  add
 r  re-add
 f  forget
@@ -239,11 +234,11 @@ EOF
 		esac
 		command chezmoi "$cmd" "$@"
 	}
-	if command -v git >/dev/null; then
-		alias dot='git -C "$(chezmoi source-path)"'
-		alias dots='git -C "$(chezmoi source-path)" status'
-		alias dotl='git -C "$(chezmoi source-path)" lg' # log + format
-	fi
+if command -v git >/dev/null; then
+	alias dot='git -C "$(chezmoi source-path)"'
+	alias dots='git -C "$(chezmoi source-path)" status'
+	alias dotl='git -C "$(chezmoi source-path)" lg' # log + format
+fi
 fi
 
 if [ -d "${HOME}/dev" ]; then
@@ -263,9 +258,9 @@ if command -v tmux >/dev/null; then
 			tmux "$@"
 		fi
 	}
-	if [ -f "${HOME}/.bashrc_tmux" ]; then
-		source "${HOME}/.bashrc_tmux"
-	fi
+if [ -f "${HOME}/.bashrc_tmux" ]; then
+	source "${HOME}/.bashrc_tmux"
+fi
 fi
 
 # Dlang: add compilers (latest installed) to PATH.
@@ -289,6 +284,9 @@ if [ -d "${HOME}/.pyenv" ]; then
 		export PATH="${PYENV_ROOT}/bin:$PATH"
 		eval "$(pyenv init -)"
 	fi
+else
+	# only one with notification, because this is a WIP
+	echo "missing '${HOME}/.pyenv/'; remove this section from .bashrc?" >&2
 fi
 
 #
