fix up bashrc; update git config (more resilient + able to split up)

diff --git a/dot_bashrc b/dot_bashrc
--- a/dot_bashrc
+++ b/dot_bashrc
@@ -112,9 +112,6 @@ if ! shopt -oq posix; then
 	fi
 fi
 
-# Necessary for gpg unlock prompt to work.
-export GPG_TTY="$(tty)"
-
 # Use the XDG env vars.
 export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"
 [ -d "${XDG_CONFIG_HOME}" ] || mkdir -p "${XDG_CONFIG_HOME}"
@@ -134,6 +131,37 @@ esac
 # Set PATH so it includes user's private bin if it exists.
 if [ -d "$HOME/.local/bin" ]; then
 	export PATH="$HOME/.local/bin:$PATH"
+fi
+
+# Extra bin's
+
+# Dlang: add compilers (latest installed) to PATH.
+if [ -f "${HOME}/dlang/install.sh" ]; then
+	for c in ldc dmd; do
+		tmp="$("${HOME}/dlang/install.sh" get-path "$c" 2>/dev/null)"
+		if [ $? -eq 0 ] && [ -n "tmp" ]; then
+			PATH="$(dirname "$tmp"):${PATH}"
+		fi
+		tmp=
+	done
+fi
+if command -v ldc2 >/dev/null; then
+	alias ldc=ldc2
+fi
+# Go
+if [ -d "${HOME}/go/bin" ]; then
+	PATH="${HOME}/go/bin:${PATH}"
+fi
+# pyenv configuration
+if [ -d "${HOME}/.pyenv" ]; then
+	export PYENV_ROOT="$HOME/.pyenv"
+	if [ -d "${PYENV_ROOT}/bin" ]; then
+		export PATH="${PYENV_ROOT}/bin:$PATH"
+		eval "$(pyenv init -)"
+	fi
+else
+	# only one with notification, because this is a WIP
+	echo "missing '${HOME}/.pyenv/'; remove this section from .bashrc?" >&2
 fi
 
 # Adjust PS1 for subshells that would be easy to forget (don't show multiple
@@ -162,6 +190,9 @@ PS1="\n${PS1::-3}\n"'\[$(ps1_prompt)\]'"\$\[\033[0m\] "
 #
 # Helpers
 #
+
+# Necessary for gpg unlock prompt to work.
+export GPG_TTY="$(tty)"
 
 alias ls='ls -FG' # G=color, F=trailing type indicator (dir=/ exe=*, ...)
 if command -v eza >/dev/null; then
@@ -258,35 +289,12 @@ if command -v tmux >/dev/null; then
 			tmux "$@"
 		fi
 	}
-if [ -f "${HOME}/.bashrc_tmux" ]; then
-	source "${HOME}/.bashrc_tmux"
-fi
-fi
-
-# Dlang: add compilers (latest installed) to PATH.
-if [ -f "${HOME}/dlang/install.sh" ]; then
-	for c in ldc dmd; do
-		tmp="$("${HOME}/dlang/install.sh" get-path "$c" 2>/dev/null)"
-		if [ $? -eq 0 ] && [ -n "tmp" ]; then
-			PATH="$(dirname "$tmp"):${PATH}"
-		fi
-		tmp=
-	done
-fi
-if command -v ldc2 >/dev/null; then
-	alias ldc=ldc2
-fi
-
-# pyenv configuration
-if [ -d "${HOME}/.pyenv" ]; then
-	export PYENV_ROOT="$HOME/.pyenv"
-	if [ -d "${PYENV_ROOT}/bin" ]; then
-		export PATH="${PYENV_ROOT}/bin:$PATH"
-		eval "$(pyenv init -)"
+	if [ -f "${HOME}/.bashrc_tmux" ]; then
+		source "${HOME}/.bashrc_tmux"
 	fi
-else
-	# only one with notification, because this is a WIP
-	echo "missing '${HOME}/.pyenv/'; remove this section from .bashrc?" >&2
+fi
+if command -v fx >/dev/null; then
+	export FX_NO_MOUSE=
 fi
 
 #
